export  const ActionTypes = {
    FETCH_PRODUCTS : 'FETCH_PRODUCTS',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    SUB_QUANTITY: 'SUB_QUANTITY',
    ADD_QUANTITY: 'ADD_QUANTITY'
}